In [ ]:
!pip3 install numpy

In [25]:
import numpy as np

# Random Numbers
- rand()
- randn()
- ranf()
- randinit()

In [26]:
# rand [0 , 1)
rand_array = np.random.rand(6)
rand_array

array([0.84376006, 0.44855921, 0.80543189, 0.06811014, 0.34330073,
       0.50144818])

In [27]:
randn_array = np.random.randn(5)
randn_array

array([-0.45337275,  0.93399081, -0.03789551, -0.00739303, -0.40745526])

In [28]:
randint_array = np.random.randint(1, 10, size=5)
randint_array

array([5, 8, 3, 1, 6])

In [29]:
randint_array = np.random.randint(1, 10, size=(2,5))
randint_array

array([[1, 3, 1, 6, 6],
       [5, 7, 9, 3, 9]])

# Datatype

# Number Data type: 
- (int8, int16, int32, int64) (Positive/Negative)
- (uint8, uint16, uint32, uint64) (Positive) u => unsigned
- (float16, float32, float64)

# Boolean
- bool

# Object
- object (mixed data-type)

# Date & Time type
- datetime64  (Data & Time represent)
- timedelta64 (Time difference between dates)

In [36]:
int_array = np.array([1, 2, 3, 4000], dtype=np.uint16)

In [37]:
int_array.dtype

dtype('uint16')

In [38]:
int_array

array([   1,    2,    3, 4000], dtype=uint16)

In [41]:
float_array = int_array.astype(np.float16)
float_array

array([1.e+00, 2.e+00, 3.e+00, 4.e+03], dtype=float16)

In [42]:
float_array.dtype

dtype('float16')

In [45]:
string_array = np.array(["Hello", "world"], dtype=np.bytes_)
string_array

array([b'Hello', b'world'], dtype='|S5')

In [47]:
date_array = np.array(['2026-01-01', '2026-01-02'], dtype=np.datetime64)
date_array

array(['2026-01-01', '2026-01-02'], dtype='datetime64[D]')

In [49]:
date_dif = date_array - np.datetime64('2025-11-01')
date_dif

array([61, 62], dtype='timedelta64[D]')

# Arthmetic 
- np_array + np_array , np.add(a1, a2)
- np_array - np_array , np.subtract(a1, a2)
- np_array * np_array , np.multiply(a1, a2)
- ...

In [50]:
prices = np.array([10, 20, 30, 40])

In [51]:
prices  = prices + 5
prices

array([15, 25, 35, 45])

In [52]:
a1 = np.array([10, 20, 30, 40])
a2 = np.array([100, 200, 300, 400])
a3 = a1 + a2
a3

array([110, 220, 330, 440])