In [74]:
!pip3 install numpy


[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip


In [3]:
import numpy as np

# Random Numbers
- rand()
- randn()
- ranf()
- randinit()

In [4]:
# rand [0 , 1)
rand_array = np.random.rand(6)
rand_array

array([0.35783519, 0.19790426, 0.0192082 , 0.7522307 , 0.91727226,
       0.82986132])

In [7]:
randn_array = np.random.randn(50)
randn_array

array([-0.52061673,  0.24905031,  0.75010813,  1.16163149,  0.52178264,
       -0.20801815,  0.36343522,  0.34562009, -1.36369361, -1.60778717,
        1.25628952,  0.87078225,  1.32969786, -1.30948736, -2.25993244,
       -0.90436234,  0.00331774,  0.82471015, -0.01339615, -1.4318586 ,
       -0.22774099,  0.75140772, -2.50561088, -0.14255822,  0.87163821,
        1.11295148,  0.52398606, -0.35042272, -0.54057844, -0.07823132,
        0.5405503 ,  0.4052186 , -2.35697853,  0.62242227,  0.11667653,
        0.33221536, -0.71865411,  1.08150645, -0.0721404 , -1.31684048,
        0.59705403,  1.24106414,  0.05230334,  1.9383482 , -1.69102008,
        0.15841937,  2.42770905,  0.42055218, -1.92861524,  0.97298416])

In [6]:
randint_array = np.random.randint(1, 10, size=5)
randint_array

array([8, 9, 4, 4, 1])

In [29]:
randint_array = np.random.randint(1, 10, size=(2,5))
randint_array

array([[1, 3, 1, 6, 6],
       [5, 7, 9, 3, 9]])

# Datatype

# Number Data type: 
- (int8, int16, int32, int64) (Positive/Negative)
- (uint8, uint16, uint32, uint64) (Positive) u => unsigned
- (float16, float32, float64)

# Boolean
- bool

# Object
- object (mixed data-type)

# Date & Time type
- datetime64  (Data & Time represent)
- timedelta64 (Time difference between dates)

In [36]:
int_array = np.array([1, 2, 3, 4000], dtype=np.uint16)

In [37]:
int_array.dtype

dtype('uint16')

In [38]:
int_array

array([   1,    2,    3, 4000], dtype=uint16)

In [41]:
float_array = int_array.astype(np.float16)
float_array

array([1.e+00, 2.e+00, 3.e+00, 4.e+03], dtype=float16)

In [42]:
float_array.dtype

dtype('float16')

In [45]:
string_array = np.array(["Hello", "world"], dtype=np.bytes_)
string_array

array([b'Hello', b'world'], dtype='|S5')

In [47]:
date_array = np.array(['2026-01-01', '2026-01-02'], dtype=np.datetime64)
date_array

array(['2026-01-01', '2026-01-02'], dtype='datetime64[D]')

In [49]:
date_dif = date_array - np.datetime64('2025-11-01')
date_dif

array([61, 62], dtype='timedelta64[D]')

# Arthmetic 
- np_array + np_array , np.add(a1, a2)
- np_array - np_array , np.subtract(a1, a2)
- np_array * np_array , np.multiply(a1, a2)
- ...

In [4]:
prices = np.array([10, 20, 30, 40])

In [5]:
prices  = prices + 5
prices

array([15, 25, 35, 45])

In [6]:
a1 = np.array([10, 20, 30, 40])
a2 = np.array([100, 200, 300, 400])
a3 = a1 + a2
a3

array([110, 220, 330, 440])

In [7]:
mul_result = a1 * a2
mul_result

array([ 1000,  4000,  9000, 16000])

In [9]:
div_result = a2 / a1
div_result

array([10., 10., 10., 10.])

In [11]:
pow_arr = np.array([1, 2, 3, 4])
pow_arr = np.power(pow_arr, 2)
pow_arr

array([ 1,  4,  9, 16])

# Arithmetic Function
- sum
- prod
- cumsum
- cumprod
- min
- max
- mean
- ...

In [13]:
arr = np.array([1, 2, 3, 4])
arr_sum = np.sum(arr)
arr_sum

np.int64(10)

In [15]:
arr_prod = np.prod(arr)
arr_prod

np.int64(24)

In [16]:
arr_cumsum = np.cumsum(arr)
arr_cumsum

array([ 1,  3,  6, 10])

In [17]:
arr_cumprod = np.cumprod(arr)
arr_cumprod

array([ 1,  2,  6, 24])

In [18]:
min_value = np.min(arr)
min_value

np.int64(1)

In [19]:
max_value = np.max(arr)
max_value

np.int64(4)

In [20]:
percentile = np.percentile(arr, 50)
percentile

np.float64(2.5)

In [21]:
min_index = np.argmin(arr)
min_index

np.int64(0)

In [22]:
max_index = np.argmax(arr)
max_index

np.int64(3)

In [28]:
# 5 X 5 Metric with random values. Find maxium value in each row.
matrix = np.random.randint(1, 100, size=(5, 5))
matrix.shape

(5, 5)

In [24]:
# axis = 0 (column)
# axis = 1 (row)
row_max = np.max(matrix, axis=1)
row_max

array([87, 89, 85, 99, 83])

In [27]:
col_max = np.max(matrix, axis=0)
col_max.shape

(5,)

# Shapes
- 1D array shape(n, ) n = number of element
- 2D array shape(m, n) m = number of rows, n = number of columns
- 3D array shape(d, r, c) d = number of depth, r = number of rows, c = number of columns

In [29]:
arr_1d = np.array([1, 2, 3, 4])
arr_1d

array([1, 2, 3, 4])

In [30]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr_2d.shape

(2, 3)

In [39]:
# Reshape
arr = np.array([1, 2, 3, 4, 5, 6])
reshape = arr.reshape(2, 3)
reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr_1d = arr_2d.flatten()
arr_1d

array([1, 2, 3, 4, 5, 6])

In [47]:
# Resize
arr = np.array([1, 2, 3, 4, 5, 6])
resize = np.resize(arr, (4, 4))
resize

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [48]:
# Add a new axis
arr = np.array([1, 2, 3, 4])
expend = arr[:, np.newaxis]
expend

array([[1],
       [2],
       [3],
       [4]])

In [50]:
# Remove a axis
array = np.array([[[1, 2, 3, 4]]])
squeeze = np.squeeze(array)
squeeze

array([1, 2, 3, 4])

In [51]:
# 1D array with 12 values you have to convert it to 3 X 4?
arr = np.array([1, 2, 3, 4, 5, 6, 11, 12, 13, 14, 15, 16])
reshape = arr.reshape(3, 4)
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6, 11, 12],
       [13, 14, 15, 16]])

In [53]:
# 4 x 4 with random values diagonal element
matrix = np.random.randint(1, 100, size=(4, 4))
matrix

array([[78, 39, 38, 71],
       [25, 64, 90, 34],
       [86, 49, 26, 96],
       [60,  6, 91, 50]])

In [54]:
result = np.diag(matrix)
result

array([78, 64, 26, 50])

# Broad-casting
```
   A1        A2      Result
 (3, 3)     (3, 3)   (3, 3)
 (3, 3)     (1, 3)   (3, 3)
 (3, 3)     (3, 1)   (3, 3)
 (3, 1)     (1, 3)   (3, 3)
 (3,)       (3, 3)   (3, 3)
```

In [58]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [59]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a3 = a1 + a2
a3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [64]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[1, 2, 3]])
a3 = a1 + a2
a3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [65]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[1], [2], [3]])
a3 = a1 + a2
a3

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [66]:
a1 = np.array([[1, 2, 3]])
a2 = np.array([[1], [2], [3]])

In [67]:
a1

array([[1, 2, 3]])

In [68]:
a2

array([[1],
       [2],
       [3]])

In [69]:
a3 = a1 + a2
a3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [70]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a1

array([1, 2, 3])

In [71]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a3 = a1 + a2
a3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [75]:
# Indexing & Slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[3])

10
40


In [76]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
p_arr2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
p_arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [78]:
p_arr2d[1][1]

5

In [79]:
arr2d[1,1]

np.int64(5)

In [80]:
arr2d[2,2]

np.int64(9)

In [81]:
arr2d[1,2]

np.int64(6)

In [82]:
# Slicing
# array[start:stop:step]
# - start: Starting index (including)
# - stop: End index (exclusive)
# - step size (default = 1)

In [91]:
arr = np.array([10, 20, 30, 40, 50])
arr[1:4]

array([20, 30, 40])

In [92]:
arr[1:5:2]

array([20, 40])

In [93]:
arr[:5] # start = 0 and end = 5

array([10, 20, 30, 40, 50])

In [95]:
arr[1:] # start = 1 and end = len of array

array([20, 30, 40, 50])

In [96]:
arr[::2] # start = 1 and end = len of array, event second element

array([10, 30, 50])

In [98]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
arr2d[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [104]:
arr2d[:, 0]

array([1, 4, 7])

In [105]:
arr2d[1, :]

array([4, 5, 6])

In [106]:
arr = np.array([10, 20, 30, 40, 50])

In [107]:
arr[-1] # len - 1 = 5 - 1 = 4

np.int64(50)

In [108]:
arr[-3:]

array([30, 40, 50])

In [109]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
arr2d[-1, -2]

np.int64(8)

In [113]:
arr2d[-2:, -2:]

array([[5, 6],
       [8, 9]])

In [114]:
# Boolean Indexing
age = np.array([10, 18, 55, 34, 12, 7, 90, 5])
age

array([10, 18, 55, 34, 12,  7, 90,  5])

In [119]:
age[age >= 18] # filter the data where age >= 18

array([18, 55, 34, 90])

In [117]:
age[np.array([False, False, False, False, False, False, False, True])]

array([5])

In [120]:
# Fancy Index
arr = np.array([10, 18, 55, 34, 12, 7, 90, 5])
index = [0, 2, 4, 6]
arr[index]

array([10, 55, 12, 90])

In [121]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
rows = [0, 1, 2]
cols = [2, 1, 0]
arr2d[rows, cols]

array([3, 5, 7])

In [124]:
# Practice Qustion
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# reverse row of 2d array
arr2d[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [125]:
arr = np.array([10, 18, 55, 34, 12, 7, 90, 5])
arr[::3]

array([10, 34, 90])

In [135]:
arr = np.array([10, 18, 55, 34, 12, 7, 90, 5])
filter_odd = arr % 2 != 0
result = arr[filter_odd]
filter_gt_10 = result > 10
result = result[filter_gt_10]
result

array([55])

In [137]:
# nditer -> way to loop the numpy array
# np.nditer(op, flags, op_flags)
# - op (input array)
# - flags
# - op_flags

In [143]:
arr = np.array([10, 18, 55, 34, 12, 7, 90, 5])
for element in np.nditer(arr):
    print(element, end=" ")

11 19 56 35 13 8 91 6 

In [144]:
arr

array([10, 18, 55, 34, 12,  7, 90,  5])